name: back_projeto_integrador
description: A server app using the shelf package and Docker.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_modular: ^2.1.0
  shelf_cors_headers: ^0.1.5
  uuid: ^3.0.7
  password_hash:
    git:
      url: https://github.com/Jay-Tezsure/dart-password-hash.git
      ref: null-safety
  dart_jsonwebtoken: ^2.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.4

