name: back_projeto_integrador
description: A server app using the shelf package and Docker.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0'

dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_modular: ^2.1.0
  shelf_cors_headers: ^0.1.5
  uuid: ^3.0.7
  postgres: ^2.6.1
  dotenv_gen: ^0.0.2
  collection: ^1.17.2
  password_hash:
    git:
      url: https://github.com/Jay-Tezsure/dart-password-hash.git
      ref: null-safety
  dart_jsonwebtoken: ^2.8.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
  dotenv_gen_runner: ^0.0.3
  build_runner: ^2.4.5

